<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_blog</name>
   <tag></tag>
   <elementGuidId>a78158a5-7882-4b81-a6ca-b5e80068f2e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/nav/div/nav/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.NavigationItems_navItem__4q_Mz.NavigationItems_navActive__P0Y1m > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;blog&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d00670f0-1318-4795-a538-1d2fc0eb1219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blog/</value>
      <webElementGuid>3e50c726-c29b-4ca6-a74f-ac7d6a981077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>blog</value>
      <webElementGuid>edbe4f53-49c3-40c3-b63a-928bdfc747a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Layout_layout__1y4NW&quot;]/nav[@class=&quot;Navigation_navigation__9_c3G Navigation_translateZero__YSmej&quot;]/div[@class=&quot;Navigation_navMargin__uglXE&quot;]/nav[@class=&quot;Navigation_navItems__v_2Wk&quot;]/ul[@class=&quot;NavigationItems_navItems__RnAdA&quot;]/li[@class=&quot;NavigationItems_navItem__4q_Mz NavigationItems_navActive__P0Y1m&quot;]/a[1]</value>
      <webElementGuid>8da6df21-62a2-4fb9-acab-7935193c8cd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div/nav/ul/li[5]/a</value>
      <webElementGuid>752d838a-4454-418c-99e7-8cc00542680d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'blog')]</value>
      <webElementGuid>2bf0feeb-6805-4cea-aa44-25415ea50023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='portfolio'])[1]/following::a[1]</value>
      <webElementGuid>97fefc1b-9eff-4d9d-a250-cee371cd455c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='about'])[1]/following::a[2]</value>
      <webElementGuid>7a5e2369-e6f1-4f6e-92d1-4106fe85f646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='team'])[1]/preceding::a[1]</value>
      <webElementGuid>40b94d4b-f4ef-4dca-abbd-1ae5ae2d19ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='client referral'])[1]/preceding::a[2]</value>
      <webElementGuid>3d28b276-3728-465d-b108-d6a8e5bb1e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='blog']/parent::*</value>
      <webElementGuid>f480d163-bd1d-4b2c-906f-588ef96adf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/blog/')]</value>
      <webElementGuid>7bc31793-622d-467a-ada6-aaf85ef31400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>c56d0a01-bcc5-40d1-b4c6-33dc9fe5c458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blog/' and (text() = 'blog' or . = 'blog')]</value>
      <webElementGuid>4d95da8b-674c-4700-a4d5-aa0d718cc69f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
